env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 2015
  sourceType: module
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - warn
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
  no-console:
    - off
  no-unused-vars:
    - warn
  max-len:
    - off
    
